export const destinations = [
  {
    id: "paris",
    name: "Paris",
    country: "France",
    emoji: "🗼",
    description: "City of Light, romance and world-class art",
    mapQuery: "Paris France",
    hotelLink: "https://www.booking.com/city/fr/paris.html",
    weatherQuery: "Paris France weather",
  },
  {
    id: "tokyo",
    name: "Tokyo",
    country: "Japan",
    emoji: "⛩️",
    description: "Ultra-modern meets ancient tradition",
    mapQuery: "Tokyo Japan",
    hotelLink: "https://www.booking.com/city/jp/tokyo.html",
    weatherQuery: "Tokyo Japan weather",
  },
  {
    id: "dubai",
    name: "Dubai",
    country: "UAE",
    emoji: "🏙️",
    description: "Desert luxury and futuristic skylines",
    mapQuery: "Dubai UAE",
    hotelLink: "https://www.booking.com/city/ae/dubai.html",
    weatherQuery: "Dubai UAE weather",
  },
  {
    id: "istanbul",
    name: "Istanbul",
    country: "Turkey",
    emoji: "🕌",
    description: "Where East meets West across two continents",
    mapQuery: "Istanbul Turkey",
    hotelLink: "https://www.booking.com/city/tr/istanbul.html",
    weatherQuery: "Istanbul Turkey weather",
  },
  {
    id: "newyork",
    name: "New York",
    country: "USA",
    emoji: "🗽",
    description: "The city that never sleeps",
    mapQuery: "New York USA",
    hotelLink: "https://www.booking.com/city/us/new-york.html",
    weatherQuery: "New York USA weather",
  },
  {
    id: "rome",
    name: "Rome",
    country: "Italy",
    emoji: "🏛️",
    description: "Eternal city of history and cuisine",
    mapQuery: "Rome Italy",
    hotelLink: "https://www.booking.com/city/it/rome.html",
    weatherQuery: "Rome Italy weather",
  },
  {
    id: "bali",
    name: "Bali",
    country: "Indonesia",
    emoji: "🌴",
    description: "Island of temples, rice fields and surf",
    mapQuery: "Bali Indonesia",
    hotelLink: "https://www.booking.com/region/id/bali.html",
    weatherQuery: "Bali Indonesia weather",
  },
  {
    id: "barcelona",
    name: "Barcelona",
    country: "Spain",
    emoji: "🎨",
    description: "Gaudí, beaches and vibrant nightlife",
    mapQuery: "Barcelona Spain",
    hotelLink: "https://www.booking.com/city/es/barcelona.html",
    weatherQuery: "Barcelona Spain weather",
  },
];